### ISSUE TITLE
error when trying to join clutter app

### ISSUE THREAD

**Issue by christopherreay** [metacurrency/holochain#457]
This is from the latest master of clutter as of 6th October 2017
and a pull of master of holochain  as of 5th October 2017.

I know that @zippy mentioned there were known issues with clutter. 
can I help? When will this be sorted out? It would be really good to have an app to work on because there are some subtletes with presenting UI's through cloud9 that I have to work through.

xx

```bash
dayzee:~/workspace/holochainApps/myClutter (master) $ hcadmin join . myClutter
validate commit: handle
validate put: handle
dayzee@holo.host is QmfJMPWHYvcNaPnBS4kmSR79m8VcgdxE36TmaEBSK6qSFb
validate commit: handle_links
validate link: handle_links
validate commit: directory_links
validate link: directory_links
panic: cleanup after failed gen not implemented!  Error was: In 'holodex' zome: Error executing genesis: ReferenceError: 'genesis' is not defined

goroutine 1 [running]:
github.com/metacurrency/holochain.(*Holochain).GenChain.func1(0xc4206d3798)
        /home/ubuntu/workspace/go/src/github.com/metacurrency/holochain/holochain.go:424 +0xc2
github.com/metacurrency/holochain.(*Holochain).GenChain(0xc42042c000, 0xc420145920, 0x22, 0x30, 0x18b2760, 0xc420825210)
        /home/ubuntu/workspace/go/src/github.com/metacurrency/holochain/holochain.go:465 +0x676
github.com/metacurrency/holochain.(*Service).GenChain(0xc42015a600, 0x7fff072c3500, 0x9, 0xc420144e70, 0x21, 0xc420144e01)
        /home/ubuntu/workspace/go/src/github.com/metacurrency/holochain/service.go:811 +0x65
main.genChain(0xc42015a600, 0x7fff072c3500, 0x9, 0xc420144e70, 0x21)
        /home/ubuntu/workspace/go/src/github.com/metacurrency/holochain/cmd/hcadmin/hcadmin.go:261 +0x5a
main.setupApp.func3(0xc4201229a0, 0x0, 0xc4201229a0)
        /home/ubuntu/workspace/go/src/github.com/metacurrency/holochain/cmd/hcadmin/hcadmin.go:132 +0x22d
github.com/urfave/cli.HandleAction(0xf37420, 0xc42014c8c0, 0xc4201229a0, 0xc420101400, 0x0)
        /home/ubuntu/workspace/go/src/github.com/urfave/cli/app.go:490 +0xd4
github.com/urfave/cli.Command.Run(0x10bb9db, 0x4, 0x0, 0x0, 0xc420150180, 0x1, 0x1, 0x10f2a3e, 0x54, 0x0, ...)
        /home/ubuntu/workspace/go/src/github.com/urfave/cli/command.go:210 +0xb6e
github.com/urfave/cli.(*App).Run(0xc42006b040, 0xc4200102c0, 0x4, 0x4, 0x0, 0x0)
        /home/ubuntu/workspace/go/src/github.com/urfave/cli/app.go:255 +0x76f
main.main()
        /home/ubuntu/workspace/go/src/github.com/metacurrency/holochain/cmd/hcadmin/hcadmin.go:253 +0x57
```

**Comment by christopherreay** [comment]
Ive also tried holochat, and there are similar errors there. The one in holochat, which is "getLink" doesnt exist, I recognise from a recent ticket of changing the name to getLinks.

What is the priority of fixing the Apps in the dev stream? Its pretty high in my hackathon stream. Also I have a guy who is looking to spend time doing app development... which might not be terrible to engage him in that process, though we are not paying him yet, apart from room and board

**Comment by zippy** [comment]
Hey.  Here's the branch that's working with current master: https://github.com/Holochain/clutter/tree/pre-hashtag  

Priority quite high in my mind.  That's what @rayzer42 is working on full time, and I want to bring on another person to do, very important accountability.

**Comment by zippy** [comment]
What this means is that you can't use `hcdev init -cloneExample` because it always goes from master.  Instead you have to clone that branch manually and do your join from that.  status is that @rayzer42 has completed the anchors mixin cleanup, and is now using for the clutter cleanup, which is scheduled to be completed by Mon.  In the mean-time the old pre-hashtag release is what I'm using for testing apps.  I will also do a similar short-term cleanup of holochat so that it works with current master later today.
